# File Options
files:
  include: 'src/scss/**/*.scss'
rules:
  indentation: 2
  no-trailing-whitespace: 2
  no-empty-rulesets: 2
  property-sort-order: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  brace-style: 0
  nesting-depth: 0
  no-qualifying-elements: 0
  class-name-format: 0
  no-css-comments: 0
  no-color-literals: 2
  no-color-keywords: 2
  final-newline: 0
  placeholder-in-extend: 0
  no-duplicate-properties: 2
  extends-before-declarations: 0
  empty-line-between-blocks: 0
  no-misspelled-properties: 2
  leading-zero:
    - 2
    - include: true
  hex-notation:
    - 2
    - style: uppercase
  no-mergeable-selectors: 2
  mixins-before-declarations: 2